### ISSUE TITLE
bug: deploy first move contract through aptos CLI and unable to clone movementlabsxyz/aptos-core

### ISSUE THREAD

**Issue by jcstein** [movementlabsxyz/movement-docs#110]
Follow-up to: https://github.com/movementlabsxyz/aptos-core/issues/112

As a result of not being able to clone or install movementlabsxyz/aptos-core, I decided to use `brew install aptos`

When attempting to publish the demo contract, it errors:

```
aptos move publish
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-framework.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING hello_blockchain
package size 1975 bytes
{
  "Error": "Simulation failed with status: CODE_DESERIALIZATION_ERROR\nExecution failed with message: Backtrace: Backtrace [\n    { fn: \"move_binary_format::errors::PartialVMError::finish\" },\n    { fn: \"aptos_vm::aptos_vm::AptosVM::deserialize_module_bundle\" },\n    { fn: \"aptos_vm::aptos_vm::AptosVM::resolve_pending_code_publish\" },\n    { fn: \"aptos_vm::aptos_vm::AptosVM::execute_script_or_entry_function\" },\n    { fn: \"aptos_vm::aptos_vm::AptosSimulationVM::create_vm_and_simulate_signed_transaction\" },\n    { fn: \"aptos_api::transactions::TransactionsApi::simulate\" },\n    { fn: \"aptos_api::transactions::TransactionsApi::simulate_transaction::{{closure}}::{{closure}}\" },\n    { fn: \"<tracing::instrument::Instrumented<T> as core::future::future::Future>::poll\" },\n    { fn: \"tokio::runtime::task::core::Core<T,S>::poll\" },\n    { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll\" },\n    { fn: \"tokio::runtime::blocking::pool::Inner::run\" },\n    { fn: \"std::sys_common::backtrace::__rust_begin_short_backtrace\" },\n    { fn: \"core::ops::function::FnOnce::call_once{{vtable.shim}}\" },\n    { fn: \"std::sys::pal::unix::thread::Thread::new::thread_start\" },\n    { fn: \"start_thread\" },\n    { fn: \"clone\" },\n]"
}
```

With some help from Claude, I got closer and the [tx lands on the explorer](https://explorer.movementnetwork.xyz/txn/157814317?network=testnet) although it fails anyways:

```
aptos move publish --skip-fetch-latest-git-deps --included-artifacts none --override-size-check --max-gas 20000 --gas-unit-price 100
Compiling, may take a little while to download git dependencies...
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING hello_blockchain
package size 1293 bytes
Transaction submitted: https://explorer.aptoslabs.com/txn/0x2e144f0625104d624f66a11f8f81332528db8192d925d7dc30f2e2849abbff7a?network=testnet
{
  "Error": "API error: Unknown error Transaction committed on chain, but failed execution: CODE_DESERIALIZATION_ERROR"
}
```

My `~/.aptos/config.yaml` is as follows, except with my private key etc:

```
---
profiles:
  default:
    network: Testnet
    private_key: "redacted"
    public_key: "redacted"
    account: e69c0875d4e04984cfc02b661d2d61fd12a2835347703b0a21efefab40fd2198
    rest_url: "https://aptos.testnet.porto.movementlabs.xyz/v1/"
    faucet_url: "https://faucet.testnet.porto.movementlabs.xyz/"
```

and my `~/hello-chain/Move.toml` is:

```toml
[package]
name = "hello_blockchain"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = "0xe69c0875d4e04984cfc02b661d2d61fd12a2835347703b0a21efefab40fd2198"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "main"
subdir = "aptos-framework"

[dev-dependencies]
```
